# Generated by Django 5.2.12 on 2026-03-23 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlists',
            old_name='playlist',
            new_name='playlist_id',
        ),
        migrations.RenameField(
            model_name='savedplaylists',
            old_name='playlist_id',
            new_name='playlist',
        ),
    ]
