# Generated by Django 5.2.12 on 2026-03-24 10:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artist', '0003_albums'),
    ]

    operations = [
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_private', models.BooleanField(default=False)),
                ('file', models.FileField(upload_to='uploads')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artist.artist')),
            ],
            options={
                'unique_together': {('title', 'artist')},
            },
        ),
        migrations.CreateModel(
            name='SongTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=25)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('song_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='song.songs')),
            ],
            options={
                'unique_together': {('song_id', 'tag')},
            },
        ),
    ]
