# Generated by Django 5.2.12 on 2026-03-25 05:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0002_songtags_update_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
