# Generated by Django 5.2.12 on 2026-03-25 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0006_alter_songs_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SongTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='song.songs')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='song.tag')),
            ],
            options={
                'unique_together': {('song_id', 'tag')},
            },
        ),
        migrations.AddField(
            model_name='songs',
            name='tags',
            field=models.ManyToManyField(through='song.SongTag', to='song.tag'),
        ),
        migrations.DeleteModel(
            name='SongTags',
        ),
    ]
