# Generated by Django 5.2.12 on 2026-03-21 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_bio_user_created_at_user_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id',
            field=models.CharField(default=True),
        ),
    ]
