# Generated by Django 5.2.12 on 2026-03-21 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_artist',
            field=models.BooleanField(default=True),
        ),
    ]
