# Generated by Django 5.2.12 on 2026-03-21 22:36

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_is_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default=accounts.models.User.generate_unique_code, max_length=20, unique=True),
        ),
    ]
