# Generated by Django 5.2.12 on 2026-03-22 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_id'),
        ('artist', '0001_initial'),
        ('interactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='following_artists',
            field=models.ManyToManyField(related_name='followed_by_user', through='interactions.Follows', to='artist.artist'),
        ),
    ]
