# Generated by Django 5.2.12 on 2026-03-26 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_following_artists'),
        ('playlists', '0002_rename_playlist_playlists_playlist_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='saved_playlist',
            field=models.ManyToManyField(related_name='saved_playlists', through='playlists.SavedPlaylists', to='playlists.playlists'),
        ),
    ]
