# Generated by Django 5.2.12 on 2026-03-21 20:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_name', models.CharField(default='', max_length=100)),
                ('verified', models.BooleanField(default=False)),
                ('genre', models.CharField(choices=[('pop', 'Pop'), ('rock', 'Rock'), ('hiphop', 'Hip Hop'), ('jazz', 'Jazz'), ('classical', 'Classical'), ('edm', 'EDM'), ('lofi', 'Lo-fi'), ('metal', 'Metal'), ('indie', 'Indie'), ('folk', 'Folk'), ('blues', 'Blues'), ('reggae', 'Reggae'), ('country', 'Country'), ('kpop', 'K-Pop'), ('latin', 'Latin')], max_length=20)),
                ('monthly_listeners', models.IntegerField(default=0)),
                ('total_streams', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
