# Generated by Django 5.2.12 on 2026-03-22 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='total_followers',
            field=models.IntegerField(default=0),
        ),
    ]
