# Generated by Django 5.2.12 on 2026-03-24 10:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0002_artist_total_followers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Albums',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('id', models.CharField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_private', models.BooleanField(default=False)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artist.artist')),
            ],
            options={
                'unique_together': {('title', 'artist')},
            },
        ),
    ]
